#ifndef SILVERM_H
#define SILVERM_H

#define FLAGV_UNUSED 0

#define FLAGV_COINS_HIDDEN 1
#define FLAGV_SHEET_HIDDEN 2
#define FLAGV_BOOTS_HIDDEN 3
#define FLAGV_HORSESHOE_HIDDEN 4
#define FLAGV_APPLES_HIDDEN 5
#define FLAGV_BUCKET_HIDDEN 6
#define FLAGV_AXE_HIDDEN 7
#define FLAGV_BOAT_HIDDEN 8
#define FLAGV_PHIAL_HIDDEN 9
#define FLAGV_REEDS_HIDDEN 10
#define FLAGV_BONE_HIDDEN 11
#define FLAGV_SHIELD_HIDDEN 12
#define FLAGV_PLANKS_HIDDEN 13
#define FLAGV_ROPE_HIDDEN 14
#define FLAGV_RING_HIDDEN 15
#define FLAGV_JUG_HIDDEN 16
#define FLAGV_NET_HIDDEN 17
#define FLAGV_SWORD_HIDDEN 18
#define FLAGV_SILVER_PLATE_HIDDEN 19
#define FLAGV_UNIFORM_HIDDEN 20
#define FLAGV_KEY_HIDDEN 21
#define FLAGV_SEEDS_HIDDEN 22
#define FLAGV_LAMP_HIDDEN 23
#define FLAGV_BREAD_HIDDEN 24
#define FLAGV_BROOCH_HIDDEN 25
#define FLAGV_MATCHES_HIDDEN 26
#define FLAGV_STONE_OF_DESTINY_HIDDEN 27
#define FLAGV_APPLE_HIDDEN 28

#define FLAGV_BOOTS_WORN 29
#define FLAGV_BOAT_POWERED 30
#define FLAGV_BOAT_KEPT_AFLOAT 31
#define FLAGV_BOAR_CAUGHT 32
#define FLAGV_POOL_EMPTIED 33
#define FLAGV_JUG_FULL 34
#define FLAGV_GHOST_FREED 35
#define FLAGV_PARSER_PLURAL_RETRY 36
#define FLAGV_SEEDS_PLANTED 37
#define FLAGV_VINE_GROWN 38
#define FLAGV_BOOT_WEAR_COUNTER 39
#define FLAGV_SHEET_TIED_AT_WELL 40
#define FLAGV_SAFE_CODE 41
#define FLAGV_BELL_RING_COUNT 42
#define FLAGV_HORSESHOE_LOOSENED 43
#define FLAGV_COIN_COUNT 44
#define FLAGV_RUBBLE_MOVED 45
#define FLAGV_HOUND_DISTRACTED 46
#define FLAGV_POISON_PLACED 47
#define FLAGV_GRARG_SLEEPING 48
#define FLAGV_INVENTORY_HAS_ITEMS 49
#define FLAGV_LAMP_LIT 50
#define FLAGV_UNIFORM_WORN 51
#define FLAGV_THIRD_WORD_SELECTOR 52
#define FLAGV_ROPE_TIED_AT_WELL 53
#define FLAGV_CHARM_TRIO_ASSEMBLED 54
#define FLAGV_GRARG_PATROL_WARNING 55
#define FLAGV_PLAYER_DEAD 56
#define FLAGV_THIRD_WORD_ROOM_PROTECT 57
#define FLAGV_THIRD_WORD_ROOM_LEAD 58
#define FLAGV_THIRD_WORD_ROOM_HELP 59
#define FLAGV_SAID_AWAKE 60
#define FLAGV_SAID_GUIDE 61
#define FLAGV_QUEST_COMPLETE 62
#define FLAGV_WIZARD_DEFEATED 63
#define FLAGV_TROLL_TOLL_PAID 64
#define FLAGV_RATS_GONE 65
#define FLAGV_COBWEBS_CLEARED 66
#define FLAGV_ROUGH_WATER_TURN_COUNTER 67
#define FLAGV_OGBAN_DEAD 68
#define FLAGV_SAVED_ROOM 69
#define FLAGV_WIZARD_DOOR_UNLOCKED 70

#endif
